[package]
name = "application"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = { version = "1.3", features = ["v4"] }
time = "0.3"

async-trait = "0.1"
thiserror = "1"
anyhow = "1"

kernel = { path = "../kernel" }