[workspace]
members = [
  "kernel",
  "application",
  "driver",
  "server"
]
resolver = "2"


[workspace.dependencies]
lutetium = { git = "https://github.com/HalsekiRaika/lutetium", features = ["persistence"] }